version: "3.9"

services:
    web:
        image: mww-nginx
        build: .
        read_only: true
        tmpfs:
          - /tmp
          - /var/cache/nginx/
          - /run/lock
          - /var/run
        ports:
            - "8123:80"
        volumes:
            - ../app/uploads:/app/uploads:rw
        links:
            - php-fpm
    php-fpm:
        image: mww-php
        build: ../php/
        read_only: true
        volumes:
            - ../app/uploads:/app/uploads:rw
        tmpfs:
          - /tmp
          - /run/lock
          - /var/run