version: "3.9"

services:
    web:
        image: mww-nginx
        build: .
        read_only: true
        tmpfs:
          - /tmp
          - /var/cache/nginx/client_temp
          - /run/lock
        ports:
            - "8123:80"
        volumes:
            - ../app/uploads:/app/uploads:rw
        links:
            - php-fpm
    php-fpm:
        image: mww-php
        build: ./php/
        read_only: true
        volumes:
            - ../app/uploads:/app/uploads:rw