kind: Deployment # this is a deployment. service will be in other yaml
apiVersion: apps/v1
metadata: 
  name: php-fpm-nginx # name of the deployment
spec:
  selector: 
    matchLabels: 
      app: mww-php-fpm-nginx
  replicas: 1 
  template: 
    metadata: 
      labels:
        app: mww-php-fpm-nginx
    spec: 
      containers: # I should set the two containers here
        - name: mww-php-fpm 
          image: jonamade/mww-php:sandwich-sre-php
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
          - containerPort: 9000
          volumeMounts: 
          - name: mww-pvclaim
            mountPath: /app/upload
        - name: mww-nginx
          image: jonamade/mww-nginx:sandwich-sre-ningx 
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
          - containerPort: 80
          volumeMounts:
          - name: mww-pvclaim
            mountPath: /app/upload
      volumes:
      - name: mww-pvclaim
        persistentVolumeClaim:
          claimName: mww-pvc