kind: Deployment # this is a deployment. service will be in other yaml
apiVersion: apps/v1
metadata: 
  name: php-fpm # name of the deployment
spec:
  selector: 
    matchLabels: 
      app: php-fpm
  replicas: 1 
  template: 
    metadata: 
      labels:
        app: php-fpm
    spec: 
      containers: # I should set the two containers here
        - name: php-fpm 
          image: jonamade/mww-php:sandwich-sre-php
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
          - containerPort: 9000
          volumeMounts: 
          - name: mww-pvclaim
            mountPath: /app/uploads
      volumes:
      - name: mww-pvclaim
        persistentVolumeClaim:
          claimName: mww-pvc
---
kind: Deployment # this is a deployment. service will be in other yaml
apiVersion: apps/v1
metadata: 
  name: php-nginx # name of the deployment
spec:
  selector: 
    matchLabels: 
      app: mww-nginx
  replicas: 1 
  template: 
    metadata: 
      labels:
        app: mww-nginx
    spec: 
      containers:
        - name: mww-nginx
          image: jonamade/mww-nginx:sandwich-sre-nginx
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
          - containerPort: 80
          volumeMounts:
          - name: mww-pvclaim
            mountPath: /app/uploads
      volumes:
      - name: mww-pvclaim
        persistentVolumeClaim:
          claimName: mww-pvc