kind: Service # this is the service for the deployment. I'm exposing port 80 of the nginx container to port 8123
apiVersion: v1
metadata: 
  name: mww-nginx
spec:
  selector:
    app: mww-nginx
  ports:
    - port: 8123
      targetPort: 80