kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: php-fpm-nginx
spec:
  rules:
    - http:
        paths:
        - path: /(.*)
          pathType: Prefix
          backend:
              service:
                name: php-fpm 
                port:
                  number: 80 