apiVersion: v1
kind: PersistentVolume
metadata:
  name: mww-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /System/Volumes/Data/mnt/nfs_src
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mww-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi