kind: Service # this is the service for the deployment. I'm exposing port 80 of the nginx container to port 8123
apiVersion: v1
metadata: 
  name: mww-nginx
spec:
  type: NodePort
  selector:
    app: mww-nginx
  ports:
    - port: 80
      name: http
      protocol: TCP
---
kind: Service 
apiVersion: v1
metadata: 
  name: php-fpm
spec:
  selector:
    app: php-fpm
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP